site_name: Чудові бренди
site_url: https://gooroo.github.io/awesome-brands/
site_author: Serhii Olendarenko
site_description: >-
  A curated list of awesome (and awful) brands I had exprience with.

copyright: >-
  Copyright &copy; 2022 Serhii Olendarenko.
  Licenced under <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 International</a>

repo_url: https://github.com/GooRoo/awesome-brands
repo_name: GooRoo/awesome-brands
edit_uri: "" #edit/main/docs/
theme:
  name: material
  language: uk
  custom_dir: 'overrides/'
  # logo: assets/qml-colors-logo_64.png
  # favicon: assets/qml-colors-logo_32.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

#   - pymdownx.arithmatex:
#       generic: true
#   # - pymdownx.betterem:
#   #     smart_enable: all
#   - pymdownx.caret
#   - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.magiclink
#   - pymdownx.smartsymbols
  - pymdownx.snippets
#   - pymdownx.superfences
#   - pymdownx.tabbed:
#       alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
#   - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - awesome-pages:
      collapse_single_pages: true
  - i18n:
      default_language: uk
      docs_structure: folder
      languages:
        uk:
          name: Українська
        en:
          name: English
  - search:
      lang: [uk, en]
  - git-revision-date-localized
  - obsidian-bridge:
      invalid_link_attributes:
        - '.invalid'
  - tags:
      # tags_file: uk/tags.md
